disabled_rules:
- trailing_comma
- file_length
- statement_position
- todo
- trailing_semicolon
- unused_closure_parameter
- empty_parentheses_with_trailing_closure
- mark
- colon
- force_try
- function_body_length
- operator_whitespace
- identifier_name
- generic_type_name
- opening_brace
- line_length
- notification_center_detachment
- nesting
- trailing_whitespace
- type_name
- force_cast
line_length: 300
excluded:
- Pods/
- Carthage/
type_body_length:
- 600 # warning
- 700 # error
variable_name_max_length:
- 60 # warning
- 80 # error
variable_name_min_length:
- 1 # warning
- 0 # error
function_body_length:
- 100 # warning
- 200 # error
